config/routes.rb
Curate::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]

  resources :ontology_terms, :documents, :annotation_jobs

  resources :ontologies do
    collection do
      get :refresh
    end

    member do
      post :toggle_hidden
    end
  end

  resources :annotations do
    collection do
      get :audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'

  root :to => 'pages#home'
end

app/views/shared/_create_popup.html.haml
#new-annotation.rounded.drop-shadow
  = simple_form_for(@new_annotation) do |f|
    = f.input :ontology_term_id, :input_html => { :class => "bp_form_complete-1150-uri" }
    = f.input :ncbo_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :field_name, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :field_value, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :starts_at, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :ends_at, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :created_by_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :curated_by_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :verified, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :status, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :document_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.submit(t('label.save'))
    = f.submit(t('label.cancel'), :class => "cancel", :id => "annotation_cancel")

%ul#annotation-menu.contextMenu
  - @ontologies.each do |ontology|
    %li{:class => "#{ontology.ncbo_id} separator"}
      %a{:href => "##{ontology.ncbo_id}"}
        = ontology.name

app/views/shared/_footer.html.haml
.footer
  == &copy; #{Time.now.year} curate

app/views/shared/_header.html.haml
.header
  = link_to(image_tag('layout/logo.png', :class => "curate-logo", :alt => "curate-logo"), root_url)
  = render(:partial => "shared/user.html.haml")
  #help
    = link_to('Help', help_url)
.clear

app/views/shared/_navigation.html.haml
.navigation
  = link_to("Home", root_url)
  = link_to("Ontologies", ontologies_url)
  = link_to("Ontology Terms", ontology_terms_url)
  = link_to("Documents", documents_url)
  = link_to("Jobs", annotation_jobs_url)
  = link_to("Annotations", annotations_url)
  = link_to("Audit", audit_annotations_url)

app/views/shared/_pagination.html.haml
- if items.num_pages == 1
  .pagination
- elsif (defined?(limit) || (items.num_pages < 10 && items.num_pages > 1))
  = render(:partial => "shared/pagination_links.html.haml", :locals => {:items => items, :klass => (defined? klass) ? klass : "data_pagination"})
- else
  .pagination
    .page_info
      Please filter your results to return fewer pages.

app/views/shared/_pagination_links.html.haml
= paginate(items)

app/views/shared/_right_click_menus.html.haml
%ul#delete-menu.contextMenu
  %li{:class => "separator"}
    %a{:href => "#delete"}
      Delete
  %li{:class => "separator"}
    %a{:href => "#cancel"}
      Cancel
%ul#annotation-type-menu.contextMenu
  %li{:class => "separator"}
    %a{:href => "#tissue"}
      Tissue
  %li{:class => "separator"}
    %a{:href => "#text"}
      Text
  %li{:class => "separator"}
    %a{:href => "#strain_used"}
      Strain Used
  %li{:class => "separator"}
    %a{:href => "#cell_used"}
      Cell Used
  %li{:class => "separator"}
    %a{:href => "#chemical_used"}
      Chemical Used

app/views/shared/_user.html.haml
#user
  = signin_signout