config/routes.rb
Curate::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]

  resources :ontology_terms, :documents, :annotation_jobs

  resources :ontologies do
    collection do
      get :refresh
    end

    member do
      post :toggle_hidden
    end
  end

  resources :annotations do
    collection do
      get :audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'

  root :to => 'pages#home'
end

app/models/document.rb
class Document
  include Mongoid::Document

  field :title, :type => String

  index :title, unique: true

  validates_presence_of :title
  validates_uniqueness_of :title

  def annotations_for(field_name)
    Annotation.where(field_name: field_name).where(document_id: self._id).order_by([:ontology_term_name, :desc])
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_filter :check_cancel, :only => [:create, :update]
  before_filter :load_document, :only => [:show, :edit, :update, :destroy]

  def index
    @query = params[:query] ? Regexp.escape(params[:query]) : ""
    page = (params[:page].to_i > 0) ? params[:page] : 1

    @documents = Document.where(:title => /^#{@query}/i).order_by([:title, :asc]).page(page)

    respond_to do |format|
      format.html {}
      format.js  {
          render(:partial => "documents_list.html.haml")
        }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    if admin?
      @new_annotation = Annotation.for_item(@document, current_user.id)
      @ontologies = Ontology.where(hidden: false).order_by([ :name, :asc ])
    end
    respond_to do |format|
      format.html
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_url, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to documents_url, notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end


  protected

  def load_document
    @document = Document.find(params[:id])
    rescue Mongoid::Errors::DocumentNotFound
      redirect_to(documents_url, warning: 'Document does not exist.')
  end

  def check_cancel
    redirect_to(documents_url) and return if (params[:commit] == t('label.cancel'))
  end

end

app/views/documents/_document.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top"}
    = link_to(highlight(document.title, @q), document_url(document))
  - if admin?
    %td{:valign => "top"}
      = link_to(t('link.edit'), edit_document_path(document))
      = link_to(t('link.delete'), document, :method => :delete)

app/views/documents/_documents_list.html.haml
%br
- if @documents.size == 0
  %p
    No documents found...
- else
  %p
    = found_count("documents", @documents)
  %p
    = render(:partial => "shared/pagination.html.haml", :locals => {:items => @documents})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "90%"}
          Title
        - if admin?
          %td{:width => "10%"}
            Action
    %tbody#staffTable
      = render(:partial => "document.html.haml", :collection => @documents)

app/views/documents/_form.html.haml
= simple_form_for(@document) do |f|
  = error_messages_for(@document)
  = f.input(:title)
  - (@document.attributes.keys-["_id", "title"]).each do |field|
    = f.input(field)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))

app/views/documents/edit.html.haml
- title t('.title')
= page_title(t('.title'))
= render(:partial => "documents/form")
= link_to('Back', documents_path)

app/views/documents/index.html.haml
= page_title("Documents")
- if admin?
  %br
  = link_to("Create document", new_document_path)
  %br
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on title:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "documents_list.html.haml")

app/views/documents/new.html.haml
- title t('.title')
= page_title(t('.title'))
= render(:partial => "documents/form")
= link_to('Back', documents_path)

app/views/documents/show.html.haml
- title(@document.title)
= page_title(@document.title)
= link_to("Back", documents_url)
%table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
  %thead
    %tr.row-header
      %th
        Field name
      %th
        Value
  - (@document.attributes.keys-['_id']).each do |field|
    %tr
      %td{width: '30%', valign: 'top'}
        %strong
          = field
      %td.annotate{valign: 'top', field_name: field, field_value: @document.do_or_do_not(field)}
        = @document.do_or_do_not(field)
    %tr.row-even
      %td{valign: 'top'}
        annotations
      %td{valign: 'top', class: "annotations-#{field}"}
        = annotation_list(@document.annotations_for(field))