config/routes.rb
Curate::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]

  resources :ontology_terms, :documents, :annotation_jobs

  resources :ontologies do
    collection do
      get :refresh
    end

    member do
      post :toggle_hidden
    end
  end

  resources :annotations do
    collection do
      get :audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'

  root :to => 'pages#home'
end

app/models/ontology.rb
class Ontology
  include Mongoid::Document

  field :ncbo_id, type: Integer
  field :current_ncbo_id, type: Integer
  field :name, type: String
  field :version, type: String
  field :stopwords, type: String
  field :expand_ontologies, type: String
  field :hidden, type: Boolean, :default => true

  index :ncbo_id, unique: true
  index :name, unique: true

  validates_presence_of :name
  validates_uniqueness_of :name

  class << self

    def which_have_annotations
      ids = Annotation.all.distinct('ncbo_id')
      Ontology.any_in(ncbo_id: ids)
    end

    def load_from_ncbo
      NcboAnnotatorService.ontologies.each do |ontology|
        o = Ontology.find_or_initialize_by(ncbo_id: ontology["virtualOntologyId"])
        if o.new_record?
          o.name = ontology['name']
          o.stopwords = ""
          o.expand_ontologies = ""
        end
        o.version = ontology['version']
        o.current_ncbo_id = ontology['localOntologyId']
        o.save
      end
    end

    def insert_terms(file, ncbo_id)
      ontology = Ontology.first(:conditions => {:ncbo_id => ncbo_id})

      term_regex = /^\[Term\]/
      id_regex = /^id: (.+)$/
      name_regex = /^name: (.+)$/
      obsolete_regex = /^is_obsolete: (.+)$/
      in_term_flag = false
      obsolete_flag = false

      File.open(file, "rb", :encoding => 'ISO-8859-1').each do |line|

        # check if we've got a term header, and set true if we do
        if result = term_regex.match(line)
          in_term_flag = true
          @ontology_term = OntologyTerm.new(:ncbo_id => ncbo_id, :ontology_id => ontology.id)
          next
        end

        # if we're not in a term, get the next line
        if !in_term_flag
          next
        end

        # we need to save the ontology
        if in_term_flag && line.blank?
          if !obsolete_flag
            @ontology_term.save
            puts "TERM: #{@ontology_term.term_id}  #{@ontology_term.name}"
          end
          in_term_flag = false
          obsolete_flag = false
        end

        # we need to match the id
        if result = id_regex.match(line)
          term_match = result[1]
          term_id = "#{ncbo_id}|#{term_match}"
          # if we've already got that id, skip it, and move out of being in the term
          if !OntologyTerm.first(:conditions => {:term_id => term_id })
            @ontology_term.term_id = term_id
          else
            in_term_flag = false
            next
          end
        end

        # get the name of the term, save it, and move out of being in the term
        if result = name_regex.match(line)
          name_match = result[1]
          @ontology_term.name = name_match
        end

        # check if there is an obsolete line, which means we don't save it
        if result = obsolete_regex.match(line)
          if result[1] == "true"
            obsolete_flag = true
          end
        end

      end
    end
  end # of self

  def toggle_hidden
    self.hidden = self.hidden? ? false : true
    save
    hidden_status
  end

  def hidden_status
    result = 'No'
    css_class = 'ontology-shown'
    if self.hidden?
      result = 'Yes'
      css_class = 'ontology-hidden'
    end
    hash = {result: result, css_class: css_class}
  end

  def update_data
    self.current_ncbo_id, self.name, self.version = NcboAnnotatorService.current_ncbo_id(self.ncbo_id)
    save!
  end

end

app/controllers/ontologies_controller.rb
class OntologiesController < ApplicationController

  before_filter :check_cancel, :only => [:create, :update]
  before_filter :admin_required, :only => [:new, :edit, :create, :update]
  before_filter :load_ontology, :only => [:show, :edit, :update, :toggle_hidden]

  def index
    @query = params[:query] ? Regexp.escape(params[:query]) : ""
    page = (params[:page].to_i > 0) ? params[:page] : 1

    @ontologies = Ontology.where(:name => /^#{@query}/i).order_by([:name, :asc]).page(page)

    respond_to do |format|
      format.html {}
      format.js  {
          render(:partial => "ontologies_list.html.haml")
        }
    end
  end

  def new
    @ontology = Ontology.new
  end

  def create
    @ontology = Ontology.new(params[:ontology])
    if @ontology.save
      redirect_to(ontologies_url, notice: "Ontology has been created.")
    else
      render(:action => :new)
    end
  end

  def edit
  end

  def update
    if @ontology.update_attributes(params[:ontology])
      redirect_to(ontologies_url, notice: 'Ontology was successfully updated.')
    else
      render(:action => :edit)
    end
  end

  def show
    page = (params[:page].to_i > 0) ? params[:page].to_i : 1
    @query = params[:query]
    @ontology_terms = OntologyTerm.where(ncbo_id: @ontology.ncbo_id, term_name: /^#{@query}/i).order_by([:term_name, :asc]).page(page)

    respond_to do |format|
      format.html {}
      format.js  {
          render(:partial => "ontologies/ontology_term_list.html.haml")
        }
    end

  end

  def refresh
    Ontology.load_from_ncbo
    redirect_to(ontologies_url, notice: 'Ontology list was successfully updated.')
  end

  def toggle_hidden
    hash = @ontology.toggle_hidden
    render(:json => hash.to_json)
  end

  protected

  def load_ontology
    @ontology = Ontology.find(params[:id])
    rescue Mongoid::Errors::DocumentNotFound
      redirect_to(ontologies_url, warning: "That ontology does not exist.")
  end

  def check_cancel
    redirect_to(ontologies_url) and return if (params[:commit] == t('label.cancel'))
  end

end

app/views/ontologies/_form.html.haml
= form.input :name
= form.input :current_ncbo_id, :label => "Current NCBO ID"
= form.input :ncbo_id, :label => "Virtual NCBO ID"
= form.input :version
= form.input :stopwords
= form.input :hidden, :as => :select, :collection => [['Yes', true], ['No', false]], :include_blank => false, :label => "Hide:"

app/views/ontologies/_ontologies_list.html.haml
%br
- if @ontologies.size == 0
  %p
    No ontologies found...
- else
  %p
    = found_count("ontologies", @ontologies)
  %p
    = render(:partial => "shared/pagination.html.haml", :locals => {:items => @ontologies})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "40%"}
          Name
        %td{:width => "20%"}
          Version
        - if admin?
          %td{:width => "20%"}
            Stopwords
          %td{:width => "10%"}
            Hidden
          %td{:width => "10%"}
            Action
    %tbody#staffTable
      = render(:partial => "ontology.html.haml", :collection => @ontologies)

app/views/ontologies/_ontology.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top"}
    = link_to(highlight(ontology.name, @q), ontology_url(ontology))
  %td{:valign => "top"}
    = ontology.version
  - if admin?
    %td{:valign => "top"}
      = ontology.stopwords.split(',').join(', ')
    %td{:valign => "top"}
      = ontology_hidden_link(ontology)
    %td{:valign => "top"}
      = link_to(t('link.edit'), edit_ontology_path(ontology))

app/views/ontologies/_ontology_term.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top", :width => "40%"}
    = link_to(ontology_term.term_name, ontology_term_url(ontology_term))
  - if admin?
    %td{:valign => "top"}
      = annotation_percentage(ontology_term.annotations_count, ontology_term.valid_annotation_percentage)
    %td{:valign => "top"}
      = annotation_percentage(ontology_term.annotations_count, ontology_term.audited_annotation_percentage)
      - if (ontology_term.annotations_count > 0) && (ontology_term.audited_annotation_percentage < 100)
        %br
        = link_to("Audit", audit_annotations_url(:query => ontology_term.term_name, :status => "Unaudited", :ncbo_id => ontology_term.ncbo_id))

app/views/ontologies/_ontology_term_list.html.haml
%br
- if @ontology_terms.size == 0
  %p
    No ontology terms found...
- else
  %p
    = found_count("ontology term", @ontology_terms)
  %p
    = render(:partial => "shared/pagination.html.haml", :locals => {:items => @ontology_terms, :limit => false})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "60%"}
          Ontology term
        - if admin?
          %td{:width => "20%"}
            Valid
          %td{:width => "20%"}
            Audited
    %tbody
      = render(:partial => "ontologies/ontology_term.html.haml", :collection => @ontology_terms)

app/views/ontologies/edit.html.haml
- title t('.title')
= page_title(t('.title'))
= simple_form_for(@ontology) do |f|
  = error_messages_for(@ontology)
  = render(:partial => "ontologies/form", :object => f)
  = f.submit(t('label.update'))
  = f.submit(t('label.cancel'))

app/views/ontologies/index.html.haml
= page_title("Ontologies")
- if admin?
  %br
  = link_to("Create ontology", new_ontology_path)
  %br
  = link_to("Refresh ontology list", refresh_ontologies_path)
  %br
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on name:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "ontologies_list.html.haml")

app/views/ontologies/new.html.haml
- title t('.title')
= page_title(t('.title'))
%br
= simple_form_for(@ontology) do |f|
  = error_messages_for(@ontology)
  = render(:partial => "ontologies/form", :object => f)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))

app/views/ontologies/show.html.haml
= page_title("Ontology: #{@ontology.name}")
%br
= link_to('Back', ontologies_url)
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on name:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "ontologies/ontology_term_list.html.haml")