config/routes.rb
Curate::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]

  resources :ontology_terms, :documents, :annotation_jobs

  resources :ontologies do
    collection do
      get :refresh
    end

    member do
      post :toggle_hidden
    end
  end

  resources :annotations do
    collection do
      get :audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'

  root :to => 'pages#home'
end

app/models/annotation_job.rb
class AnnotationJob
  include Mongoid::Document
  include Mongoid::Timestamps

  field :ncbo_id, :type => Integer
  field :document_id, :type => String
  field :field_name, :type => String
  field :field_value, :type => String

  field :started_at, :type => DateTime
  field :finished_at, :type => DateTime

  index(
    [
      [ :ncbo_id, Mongo::ASCENDING ],
      [ :document_id, Mongo::ASCENDING ],
      [ :field_name, Mongo::ASCENDING ]
    ],
    unique: true)

  @queue = :processing

  class << self

    def perform(hash)
      case hash['action']
        when 'generate'
          self.generate_jobs(hash['ncbo_id'])
      end
    end

    def generate_jobs(ncbo_id)
      Document.all.each do |document|
        (document.attributes.keys-['_id']).each do |field_name|
          field_value = document.do_or_do_not(field_name)
          if !field_value.blank?
            Rails.logger.debug(field_value)
            job = AnnotationJob.new(ncbo_id: ncbo_id, document_id: document.id, field_name: field_name, field_value: field_value)
            if job.save
              Resque.enqueue(AnnotationProcessor, job.id)
            end
          end
        end
      end
    end
  end

end

app/controllers/annotation_jobs_controller.rb
class AnnotationJobsController < ApplicationController

  before_filter :check_cancel, :only => [:create]
  before_filter :admin_required, :except => [:status]

  def index
    page = (params[:page].to_i > 0) ? params[:page] : 1
    @annotation_jobs = AnnotationJob.order_by([:created_at, :desc]).page(page)
  end

  def new
    @annotation_job = AnnotationJob.new
    @ontologies = Ontology.where(hidden: false).order_by([ :name, :asc ])
  end

  def create
    job = AnnotationJob.new(params[:annotation_job])
    Resque.enqueue(AnnotationJob, {action: 'generate', ncbo_id: job.ncbo_id})
    redirect_to(annotation_jobs_url, notice: "Jobs have been created.")
  end

  protected

  def check_cancel
    redirect_to(annotation_jobs_url) and return if (params[:commit] == t('label.cancel'))
  end

end

app/views/annotation_jobs/_annotation_job.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top"}
    = annotation_job.document_id
  %td{:valign => "top"}
    = annotation_job.field_name
  %td{:valign => "top"}
    = annotation_job.ncbo_id
  %td{:valign => "top"}
    = date_or_pending(annotation_job.created_at)
  %td{:valign => "top"}
    = date_or_pending(annotation_job.finished_at)

app/views/annotation_jobs/_annotation_jobs_list.html.haml
%br
- if @annotation_jobs.size == 0
  %p
    No jobs found...
- else
  %p
    = found_count("jobs", @annotation_jobs)
  %p
    = render(:partial => "shared/pagination", :locals => {:items => @annotation_jobs})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "10%"}
          Document ID
        %td{:width => "10%"}
          Field
        %td{:width => "30%"}
          Ontology
        %td{:width => "25%"}
          Started at
        %td{:width => "25%"}
          Finished at
    %tbody#staffTable
      = render(:partial => "annotation_job.html.haml", :collection => @annotation_jobs)

app/views/annotation_jobs/_form.html.haml
= form.input :ncbo_id, :as => :select, :collection => @ontologies, :label_method => :name, :value_method => :ncbo_id, :include_blank => false, :label => "Ontology:"

app/views/annotation_jobs/index.html.haml
- title t(".title")
= page_title(t('.title'))
%br
%p
  = link_to(t('.new_link'), new_annotation_job_url)

.dataTable
  = render(:partial => "annotation_jobs_list.html.haml")

app/views/annotation_jobs/new.html.haml
- title t('.title')
= page_title(t('.title'))
%br
= simple_form_for(@annotation_job) do |f|
  = error_messages_for(@annotation_job)
  = render(:partial => "annotation_jobs/form.html.haml", :object => f)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))